### ISSUE TITLE
permissions?

### ISSUE THREAD

**Issue by physiciancoder** [brokiem/SimplePets#11]
where tf are the permissions??

**Comment by brokiem** [comment]
| Command | Description | Permission | Default |
| --- | --- | --- | --- |
| ```/spet``` | ```SimplePets command list``` | ```none``` | ```true``` |
| ```/spet petlist``` | ```Show all pet list``` | ```simplepets.petlist``` | ```op``` |
| ```/spet spawn``` | ```Spawning a pet``` | ```simplepets.spawn``` | ```op``` |
| ```/spet remove``` | ```Removing a pet``` | ```simplepets.remove``` | ```op``` |
| ```/spet inv``` | ```View pet inventory``` | ```simplepets.inv``` | ```true``` |
| ```/spet ride``` | ```Ride a pet``` | ```simplepets.ride``` | ```true``` |

**Comment by physiciancoder** [comment]
Is there perms for individual pets?

**Comment by brokiem** [comment]
no

**Comment by ghost** [comment]
yes
